import { forceCenter, forceCollide, forceLink, forceManyBody, forceSimulation, type Simulation, type SimulationNodeDatum } from "d3-force";
import { select } from "d3-selection";
import { zoom, zoomIdentity, type ZoomBehavior } from "d3-zoom";
import { Minus, Network, Pause, Play, Plus, RefreshCw, RotateCw, Search, X } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";

import type { ExplorerNode, GraphExplorerView } from "../lib/types";
import { buildGraphModel, connectedNodeIds, initialPosition } from "./graphModel";

interface GraphExplorerProps { graph: GraphExplorerView | null; loading: boolean; refreshingAnalytics: boolean; onRefresh: () => void; onRefreshAnalytics: () => void; }
interface ForceNode extends SimulationNodeDatum, ExplorerNode { color: string; radius: number; }
interface ForceLink { id: string; source: string | ForceNode; target: string | ForceNode; type: string; weight: number; confidence: number; }

export function GraphExplorer({ graph, loading, refreshingAnalytics, onRefresh, onRefreshAnalytics }: GraphExplorerProps) {
  const canvasRef = useRef<SVGSVGElement>(null); const viewportRef = useRef<SVGGElement>(null);
  const simulationRef = useRef<Simulation<ForceNode, undefined> | null>(null); const zoomRef = useRef<ZoomBehavior<SVGSVGElement, unknown> | null>(null);
  const [communityFilter, setCommunityFilter] = useState("all"); const [entityTypeFilter, setEntityTypeFilter] = useState("all"); const [relationTypeFilter, setRelationTypeFilter] = useState("all");
  const [linkDistance, setLinkDistance] = useState(110); const [chargeStrength, setChargeStrength] = useState(-260); const [nodeScale, setNodeScale] = useState(1); const [showLabels, setShowLabels] = useState(true); const [physicsEnabled, setPhysicsEnabled] = useState(true);
  const [selectedId, setSelectedId] = useState<string | null>(null); const [query, setQuery] = useState(""); const [size, setSize] = useState({ width: 900, height: 520 }); const [positions, setPositions] = useState<ForceNode[]>([]);
  const { nodes, links } = useMemo(() => buildGraphModel(graph, { communityId: communityFilter, entityType: entityTypeFilter, relationType: relationTypeFilter, nodeScale }), [graph, communityFilter, entityTypeFilter, relationTypeFilter, nodeScale]);
  const entityTypes = useMemo(() => [...new Set((graph?.nodes ?? []).map((node) => node.entity_type))].sort(), [graph]);
  const relationTypes = useMemo(() => [...new Set((graph?.relations ?? []).map((link) => link.type))].sort(), [graph]);
  const neighborIds = useMemo(() => connectedNodeIds(links, selectedId), [links, selectedId]);
  const selected = graph?.nodes.find((node) => node.id === selectedId) ?? null;
  const selectedRelations = useMemo(() => selectedId ? links.filter((link) => (typeof link.source === "string" ? link.source : (link.source as unknown as ForceNode).id) === selectedId || (typeof link.target === "string" ? link.target : (link.target as unknown as ForceNode).id) === selectedId) : [], [links, selectedId]);

  useEffect(() => { const element = canvasRef.current; if (!element) return; const resize = () => setSize({ width: element.clientWidth || 900, height: element.clientHeight || 520 }); resize(); const observer = new ResizeObserver(resize); observer.observe(element); return () => observer.disconnect(); }, []);
  useEffect(() => { const element = canvasRef.current; if (!element) return undefined; const behavior = zoom<SVGSVGElement, unknown>().scaleExtent([0.35, 4]).on("zoom", (event) => { select(viewportRef.current).attr("transform", event.transform.toString()); }); zoomRef.current = behavior; select(element).call(behavior); return () => { select(element).on(".zoom", null); }; }, []);
  useEffect(() => { if (!nodes.length) { setPositions([]); return; } const simulationNodes = nodes.map((node) => ({ ...node, ...initialPosition(node.id, size.width, size.height) })); const simulation = forceSimulation<ForceNode>(simulationNodes).force("link", forceLink<ForceNode, ForceLink>(links).id((node) => node.id).distance(linkDistance).strength(0.55)).force("charge", forceManyBody().strength(chargeStrength)).force("collide", forceCollide<ForceNode>().radius((node) => node.radius + 10)).force("center", forceCenter(size.width / 2, size.height / 2)).on("tick", () => setPositions([...simulationNodes])); simulationRef.current = simulation; if (!physicsEnabled) simulation.stop(); return () => { simulation.stop(); }; }, [nodes, links, size, linkDistance, chargeStrength, physicsEnabled]);
  const zoomBy = (factor: number) => { const svg = canvasRef.current; if (svg && zoomRef.current) select(svg).call(zoomRef.current.scaleBy, factor); };
  const fitGraph = () => { const svg = canvasRef.current; if (svg && zoomRef.current) select(svg).call(zoomRef.current.transform, zoomIdentity); };
  const resetSimulation = () => { simulationRef.current?.alpha(1).restart(); setPhysicsEnabled(true); };
  const findNode = (value: string) => { setQuery(value); const match = nodes.find((node) => node.canonical_name.toLowerCase().includes(value.trim().toLowerCase())); if (value.trim() && match) setSelectedId(match.id); };

  return <section className="panel knowledge-panel" id="graph" aria-labelledby="graph-heading"><div className="panel-header"><div><span className="panel-eyebrow">Knowledge Graph</span><h2 id="graph-heading" className="panel-title">Entity Network</h2></div><div className="panel-actions"><span className="badge">{graph ? `${graph.stats.entity_count} entities · ${graph.stats.relation_count} relations` : "—"}</span><button className="btn btn-ghost" onClick={onRefresh} disabled={loading} title="Refresh graph"><RefreshCw size={14} /></button></div></div>
    <div className="knowledge-toolbar"><label>Community<select value={communityFilter} onChange={(e) => setCommunityFilter(e.target.value)}><option value="all">All communities</option>{graph?.communities.map((c, i) => <option key={c.id} value={c.id}>Community {i + 1} · {c.entity_count}</option>)}</select></label><label>Type<select aria-label="Entity type" value={entityTypeFilter} onChange={(e) => setEntityTypeFilter(e.target.value)}><option value="all">All types</option>{entityTypes.map((type) => <option key={type}>{type}</option>)}</select></label><label>Relation<select aria-label="Relation type" value={relationTypeFilter} onChange={(e) => setRelationTypeFilter(e.target.value)}><option value="all">All relations</option>{relationTypes.map((type) => <option key={type}>{type}</option>)}</select></label><label className="graph-search"><Search size={14}/><input value={query} onChange={(e) => findNode(e.target.value)} placeholder="Find entity" aria-label="Find entity"/></label><button className="btn btn-ghost analytics-refresh" onClick={onRefreshAnalytics} disabled={refreshingAnalytics || !graph}><RotateCw size={14}/> Refresh analytics</button></div>
    <div className="graph-controls"><label>Distance<input aria-label="Link distance" type="range" min="40" max="220" value={linkDistance} onChange={(e) => setLinkDistance(Number(e.target.value))}/></label><label>Charge<input aria-label="Charge strength" type="range" min="-600" max="-40" value={chargeStrength} onChange={(e) => setChargeStrength(Number(e.target.value))}/></label><label>Scale<input aria-label="Node scale" type="range" min="0.5" max="1.8" step="0.1" value={nodeScale} onChange={(e) => setNodeScale(Number(e.target.value))}/></label><label><input aria-label="Show labels" type="checkbox" checked={showLabels} onChange={(e) => setShowLabels(e.target.checked)}/> Labels</label><button onClick={() => { setPhysicsEnabled((enabled) => !enabled); simulationRef.current?.stop(); }} aria-label="Toggle physics">{physicsEnabled ? <Pause size={14}/> : <Play size={14}/>}</button><button onClick={resetSimulation}>Reset simulation</button><button onClick={() => zoomBy(1.25)} aria-label="Zoom in"><Plus size={14}/></button><button onClick={() => zoomBy(0.8)} aria-label="Zoom out"><Minus size={14}/></button><button onClick={fitGraph}>Fit graph</button></div>
    <div className="graph-canvas knowledge-canvas">{nodes.length ? <svg ref={canvasRef} data-testid="d3-graph" className="d3-graph" viewBox={`0 0 ${size.width} ${size.height}`} role="img" aria-label="Force-directed entity network" onClick={() => setSelectedId(null)}><defs><marker id="graph-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z"/></marker></defs><g ref={viewportRef}><g className="d3-links">{links.map((link) => { const source = positions.find((node) => node.id === link.source); const target = positions.find((node) => node.id === link.target); return source?.x != null && target?.x != null ? <line key={link.id} x1={source.x} y1={source.y} x2={target.x} y2={target.y} strokeWidth={1 + link.weight * 2} markerEnd="url(#graph-arrow)"/> : null; })}</g><g className="d3-nodes">{positions.map((node) => node.x != null && node.y != null ? <g key={node.id} className={`d3-node ${selectedId === node.id ? "is-selected" : ""} ${selectedId && neighborIds.has(node.id) ? "is-neighbor" : ""}`} transform={`translate(${node.x},${node.y})`} onClick={(e) => { e.stopPropagation(); setSelectedId(node.id); }}><circle r={node.radius} fill={node.color}/>{showLabels && <><text dy="-0.1em">{node.canonical_name}</text><text className="d3-node-type" dy="1.25em">{node.entity_type}</text></>}<title>{node.canonical_name}</title></g> : null)}</g></g></svg> : <div className="empty-state"><Network size={28}/><p>Graph projection will appear after entity extraction completes.</p></div>}{selected && <aside className="graph-node-detail" aria-label="Selected entity"><button onClick={() => setSelectedId(null)} aria-label="Close entity details"><X size={15}/></button><span>{selected.entity_type}</span><strong>{selected.canonical_name}</strong><dl><div><dt>Connections</dt><dd>{selected.degree}</dd></div><div><dt>Importance</dt><dd>{(selected.importance * 100).toFixed(1)}%</dd></div></dl>{selectedRelations.length > 0 && <ul className="graph-node-relations" aria-label="Entity relations">{selectedRelations.map((r) => <li key={r.id}>{r.type.replaceAll("_", " ")} · {r.confidence.toFixed(2)}</li>)}</ul>}</aside>}</div></section>;
}
