"""Hard bounds for public graph API query parameters."""

MAX_NEIGHBORS = 100
MAX_NODES = 200
MAX_PATH_DEPTH = 4
MAX_PATH_RELATIONS = 200
MAX_SUBGRAPH_DEPTH = 2
MAX_SUBGRAPH_RELATIONS = 400
MAX_EXPLORER_NODES = 3_000
MAX_EXPLORER_RELATIONS = 5_000
MAX_RELATION_CITATIONS = 20
GRAPH_CANDIDATE_LIMIT = 2_000
